clear

load("state_constrained_mpc.mat")

figure(1)
plot(time, multi_sim_xc(:,1), ...
    time, multi_sim_xc(:,2), ...
    time, multi_sim_xc(:,3), ...
    time, multi_sim_xc(:,4), ...
    time, multi_sim_xc(:,5), ...
    time, multi_sim_xc(:,6), ...
    time, multi_sim_xc(:,7));
hold on
plot(time, x_ref,'--k',time, x_ref*0.9,':k', time,x_ref*1.1,':k')
hold off
ylabel('$\hat{x_c}~ (m)$','fontsize',16,'interpreter','latex')
legend('N = 13','N = 14','N = 15','N = 16','N = 17','N = 18','N = 19', 'fontsize',16,'interpreter','latex')

xlabel('Time (s)','fontsize',16,'interpreter','latex')
xticks(0:5:60);
grid on

figure(2)
plot(time, multi_sim_theta(:,1), ...
    time, multi_sim_theta(:,2), ...
    time, multi_sim_theta(:,3), ...
    time, multi_sim_theta(:,4), ...
    time, multi_sim_theta(:,5), ...
    time, multi_sim_theta(:,6), ...
    time, multi_sim_theta(:,7));
hold on
plot([0, 60], [3, 3], '--k');
plot([0, 60], [-3, -3], '--k');
hold off
ylabel('$\hat{\theta}~ (deg)$','fontsize',16,'interpreter','latex')
legend('N = 13','N = 14','N = 15','N = 16','N = 17','N = 18','N = 19', 'fontsize',16,'interpreter','latex')

xlabel('Time (s)','fontsize',16,'interpreter','latex')
xticks(0:5:60);
grid on

clear

load("unconstrained_mpc.mat")

figure(3)
plot(time, multi_sim_xc(:,1), ...
    time, multi_sim_xc(:,2), ...
    time, multi_sim_xc(:,3), ...
    time, multi_sim_xc(:,4), ...
    time, multi_sim_xc(:,5), ...
    time, multi_sim_xc(:,6), ...
    time, multi_sim_xc(:,7));
hold on
plot(time, x_ref,'--k',time, x_ref*0.9,':k', time,x_ref*1.1,':k')
hold off
ylabel('$\hat{x_c}~ (m)$','fontsize',16,'interpreter','latex')
legend('N = 13','N = 14','N = 15','N = 16','N = 17','N = 18','N = 19', 'fontsize',16,'interpreter','latex')
axis([0 60 -1 6])
xlabel('Time (s)','fontsize',16,'interpreter','latex')
xticks(0:5:60);
grid on

figure(4)
plot(time, multi_sim_theta(:,1), ...
    time, multi_sim_theta(:,2), ...
    time, multi_sim_theta(:,3), ...
    time, multi_sim_theta(:,4), ...
    time, multi_sim_theta(:,5), ...
    time, multi_sim_theta(:,6), ...
    time, multi_sim_theta(:,7));
ylabel('$\hat{\theta}~ (deg)$','fontsize',16,'interpreter','latex')
legend('N = 13','N = 14','N = 15','N = 16','N = 17','N = 18','N = 19', 'fontsize',16,'interpreter','latex')
axis([0 60 -15 15])
xlabel('Time (s)','fontsize',16,'interpreter','latex')
xticks(0:5:60);
grid on

